#!/bin/bash
echo
echo "                                                ######################"
echo "                                                # Seja bem vindo(a)! #"
echo "                                                ######################"
echo
echo "                      Lembre-se: Com grandes poderes, vem grandes responsabilidades (Tio Ben)."
echo
